import IsExistCompany from "@/components/IsExistCompany";
import SessionProvider from "@/components/session-provider";
import { getCompanyId } from "@/utils/GetCompanyId";
import { Geist, Geist_Mono } from "next/font/google";
import { ToastContainer } from "react-toastify";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const companyId = await getCompanyId();

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <SessionProvider>
          <IsExistCompany companyId={companyId} />
          {children}
          <ToastContainer />
        </SessionProvider>
      </body>
    </html>
  );
}
