export const countriesData = [
  {
    name: "United States",
    code: "US",
    phoneCode: "+1",
    currency: "USD",
    currencySymbol: "$",
  },
  {
    name: "Canada",
    code: "CA",
    phoneCode: "+1",
    currency: "CAD",
    currencySymbol: "$",
  },
  {
    name: "United Kingdom",
    code: "GB",
    phoneCode: "+44",
    currency: "GBP",
    currencySymbol: "£",
  },
  {
    name: "European Union",
    code: "EU",
    phoneCode: "+32",
    currency: "EUR",
    currencySymbol: "€",
  },
  {
    name: "Japan",
    code: "JP",
    phoneCode: "+81",
    currency: "JPY",
    currencySymbol: "¥",
  },
  {
    name: "Australia",
    code: "AU",
    phoneCode: "+61",
    currency: "AUD",
    currencySymbol: "$",
  },
  {
    name: "China",
    code: "CN",
    phoneCode: "+86",
    currency: "CNY",
    currencySymbol: "¥",
  },
  {
    name: "India",
    code: "IN",
    phoneCode: "+91",
    currency: "INR",
    currencySymbol: "₹",
  },
  {
    name: "Switzerland",
    code: "CH",
    phoneCode: "+41",
    currency: "CHF",
    currencySymbol: "CHF",
  },
  {
    name: "Brazil",
    code: "BR",
    phoneCode: "+55",
    currency: "BRL",
    currencySymbol: "R$",
  },
  {
    name: "Russia",
    code: "RU",
    phoneCode: "+7",
    currency: "RUB",
    currencySymbol: "₽",
  },
  {
    name: "South Korea",
    code: "KR",
    phoneCode: "+82",
    currency: "KRW",
    currencySymbol: "₩",
  },
  {
    name: "Mexico",
    code: "MX",
    phoneCode: "+52",
    currency: "MXN",
    currencySymbol: "$",
  },
  {
    name: "South Africa",
    code: "ZA",
    phoneCode: "+27",
    currency: "ZAR",
    currencySymbol: "R",
  },
  {
    name: "Saudi Arabia",
    code: "SA",
    phoneCode: "+966",
    currency: "SAR",
    currencySymbol: "﷼",
  },
  {
    name: "United Arab Emirates",
    code: "AE",
    phoneCode: "+971",
    currency: "AED",
    currencySymbol: "د.إ",
  },
  {
    name: "Turkey",
    code: "TR",
    phoneCode: "+90",
    currency: "TRY",
    currencySymbol: "₺",
  },
  {
    name: "Singapore",
    code: "SG",
    phoneCode: "+65",
    currency: "SGD",
    currencySymbol: "$",
  },
  {
    name: "Hong Kong",
    code: "HK",
    phoneCode: "+852",
    currency: "HKD",
    currencySymbol: "$",
  },
  {
    name: "New Zealand",
    code: "NZ",
    phoneCode: "+64",
    currency: "NZD",
    currencySymbol: "$",
  },
  {
    name: "Sweden",
    code: "SE",
    phoneCode: "+46",
    currency: "SEK",
    currencySymbol: "kr",
  },
  {
    name: "Norway",
    code: "NO",
    phoneCode: "+47",
    currency: "NOK",
    currencySymbol: "kr",
  },
  {
    name: "Denmark",
    code: "DK",
    phoneCode: "+45",
    currency: "DKK",
    currencySymbol: "kr",
  },
  {
    name: "Poland",
    code: "PL",
    phoneCode: "+48",
    currency: "PLN",
    currencySymbol: "zł",
  },
  {
    name: "Thailand",
    code: "TH",
    phoneCode: "+66",
    currency: "THB",
    currencySymbol: "฿",
  },
  {
    name: "Malaysia",
    code: "MY",
    phoneCode: "+60",
    currency: "MYR",
    currencySymbol: "RM",
  },
  {
    name: "Indonesia",
    code: "ID",
    phoneCode: "+62",
    currency: "IDR",
    currencySymbol: "Rp",
  },
  {
    name: "Philippines",
    code: "PH",
    phoneCode: "+63",
    currency: "PHP",
    currencySymbol: "₱",
  },
  {
    name: "Vietnam",
    code: "VN",
    phoneCode: "+84",
    currency: "VND",
    currencySymbol: "₫",
  },
  {
    name: "Argentina",
    code: "AR",
    phoneCode: "+54",
    currency: "ARS",
    currencySymbol: "$",
  },
  {
    name: "Chile",
    code: "CL",
    phoneCode: "+56",
    currency: "CLP",
    currencySymbol: "$",
  },
  {
    name: "Egypt",
    code: "EG",
    phoneCode: "+20",
    currency: "EGP",
    currencySymbol: "£",
  },
  {
    name: "Israel",
    code: "IL",
    phoneCode: "+972",
    currency: "ILS",
    currencySymbol: "₪",
  },
  {
    name: "Nigeria",
    code: "NG",
    phoneCode: "+234",
    currency: "NGN",
    currencySymbol: "₦",
  },
  {
    name: "Pakistan",
    code: "PK",
    phoneCode: "+92",
    currency: "PKR",
    currencySymbol: "₨",
  },
  {
    name: "Bangladesh",
    code: "BD",
    phoneCode: "+880",
    currency: "BDT",
    currencySymbol: "৳",
  },
  {
    name: "Colombia",
    code: "CO",
    phoneCode: "+57",
    currency: "COP",
    currencySymbol: "$",
  },
  {
    name: "Peru",
    code: "PE",
    phoneCode: "+51",
    currency: "PEN",
    currencySymbol: "S/",
  },
  {
    name: "Ukraine",
    code: "UA",
    phoneCode: "+380",
    currency: "UAH",
    currencySymbol: "₴",
  },
  {
    name: "Czech Republic",
    code: "CZ",
    phoneCode: "+420",
    currency: "CZK",
    currencySymbol: "Kč",
  },
  {
    name: "Hungary",
    code: "HU",
    phoneCode: "+36",
    currency: "HUF",
    currencySymbol: "Ft",
  },
  {
    name: "Romania",
    code: "RO",
    phoneCode: "+40",
    currency: "RON",
    currencySymbol: "lei",
  },
  {
    name: "Kazakhstan",
    code: "KZ",
    phoneCode: "+7",
    currency: "KZT",
    currencySymbol: "₸",
  },
  {
    name: "Qatar",
    code: "QA",
    phoneCode: "+974",
    currency: "QAR",
    currencySymbol: "﷼",
  },
  {
    name: "Kuwait",
    code: "KW",
    phoneCode: "+965",
    currency: "KWD",
    currencySymbol: "د.ك",
  },
  {
    name: "Oman",
    code: "OM",
    phoneCode: "+968",
    currency: "OMR",
    currencySymbol: "﷼",
  },
  {
    name: "Bahrain",
    code: "BH",
    phoneCode: "+973",
    currency: "BHD",
    currencySymbol: "د.ب",
  },
  {
    name: "Jordan",
    code: "JO",
    phoneCode: "+962",
    currency: "JOD",
    currencySymbol: "د.ا",
  },
  {
    name: "Lebanon",
    code: "LB",
    phoneCode: "+961",
    currency: "LBP",
    currencySymbol: "ل.ل",
  },
  {
    name: "Iceland",
    code: "IS",
    phoneCode: "+354",
    currency: "ISK",
    currencySymbol: "kr",
  },
  {
    name: "Croatia",
    code: "HR",
    phoneCode: "+385",
    currency: "HRK",
    currencySymbol: "kn",
  },
  {
    name: "Bulgaria",
    code: "BG",
    phoneCode: "+359",
    currency: "BGN",
    currencySymbol: "лв",
  },
  {
    name: "Serbia",
    code: "RS",
    phoneCode: "+381",
    currency: "RSD",
    currencySymbol: "дин",
  },
  {
    name: "Morocco",
    code: "MA",
    phoneCode: "+212",
    currency: "MAD",
    currencySymbol: "د.م.",
  },
  {
    name: "Tunisia",
    code: "TN",
    phoneCode: "+216",
    currency: "TND",
    currencySymbol: "د.ت",
  },
  {
    name: "Kenya",
    code: "KE",
    phoneCode: "+254",
    currency: "KES",
    currencySymbol: "KSh",
  },
  {
    name: "Ethiopia",
    code: "ET",
    phoneCode: "+251",
    currency: "ETB",
    currencySymbol: "Br",
  },
  {
    name: "Ghana",
    code: "GH",
    phoneCode: "+233",
    currency: "GHS",
    currencySymbol: "₵",
  },
  {
    name: "Tanzania",
    code: "TZ",
    phoneCode: "+255",
    currency: "TZS",
    currencySymbol: "TSh",
  },
  {
    name: "Uganda",
    code: "UG",
    phoneCode: "+256",
    currency: "UGX",
    currencySymbol: "USh",
  },
  {
    name: "Sri Lanka",
    code: "LK",
    phoneCode: "+94",
    currency: "LKR",
    currencySymbol: "Rs",
  },
  {
    name: "Nepal",
    code: "NP",
    phoneCode: "+977",
    currency: "NPR",
    currencySymbol: "₨",
  },
  {
    name: "Myanmar",
    code: "MM",
    phoneCode: "+95",
    currency: "MMK",
    currencySymbol: "K",
  },
  {
    name: "Cambodia",
    code: "KH",
    phoneCode: "+855",
    currency: "KHR",
    currencySymbol: "៛",
  },
  {
    name: "Laos",
    code: "LA",
    phoneCode: "+856",
    currency: "LAK",
    currencySymbol: "₭",
  },
  {
    name: "Mongolia",
    code: "MN",
    phoneCode: "+976",
    currency: "MNT",
    currencySymbol: "₮",
  },
  {
    name: "Georgia",
    code: "GE",
    phoneCode: "+995",
    currency: "GEL",
    currencySymbol: "ლ",
  },
  {
    name: "Azerbaijan",
    code: "AZ",
    phoneCode: "+994",
    currency: "AZN",
    currencySymbol: "₼",
  },
  {
    name: "Armenia",
    code: "AM",
    phoneCode: "+374",
    currency: "AMD",
    currencySymbol: "֏",
  },
  {
    name: "Belarus",
    code: "BY",
    phoneCode: "+375",
    currency: "BYN",
    currencySymbol: "Br",
  },
  {
    name: "Moldova",
    code: "MD",
    phoneCode: "+373",
    currency: "MDL",
    currencySymbol: "L",
  },
  {
    name: "Albania",
    code: "AL",
    phoneCode: "+355",
    currency: "ALL",
    currencySymbol: "L",
  },
  {
    name: "North Macedonia",
    code: "MK",
    phoneCode: "+389",
    currency: "MKD",
    currencySymbol: "ден",
  },
  {
    name: "Bosnia and Herzegovina",
    code: "BA",
    phoneCode: "+387",
    currency: "BAM",
    currencySymbol: "KM",
  },
  {
    name: "Montenegro",
    code: "ME",
    phoneCode: "+382",
    currency: "EUR",
    currencySymbol: "€",
  },
  {
    name: "Kosovo",
    code: "XK",
    phoneCode: "+383",
    currency: "EUR",
    currencySymbol: "€",
  },
  {
    name: "Venezuela",
    code: "VE",
    phoneCode: "+58",
    currency: "VES",
    currencySymbol: "Bs.S",
  },
  {
    name: "Uruguay",
    code: "UY",
    phoneCode: "+598",
    currency: "UYU",
    currencySymbol: "$",
  },
  {
    name: "Paraguay",
    code: "PY",
    phoneCode: "+595",
    currency: "PYG",
    currencySymbol: "₲",
  },
  {
    name: "Bolivia",
    code: "BO",
    phoneCode: "+591",
    currency: "BOB",
    currencySymbol: "Bs.",
  },
  {
    name: "Ecuador",
    code: "EC",
    phoneCode: "+593",
    currency: "USD",
    currencySymbol: "$",
  },
  {
    name: "Costa Rica",
    code: "CR",
    phoneCode: "+506",
    currency: "CRC",
    currencySymbol: "₡",
  },
  {
    name: "Panama",
    code: "PA",
    phoneCode: "+507",
    currency: "USD",
    currencySymbol: "$",
  },
  {
    name: "Dominican Republic",
    code: "DO",
    phoneCode: "+1",
    currency: "DOP",
    currencySymbol: "$",
  },
  {
    name: "Guatemala",
    code: "GT",
    phoneCode: "+502",
    currency: "GTQ",
    currencySymbol: "Q",
  },
  {
    name: "Honduras",
    code: "HN",
    phoneCode: "+504",
    currency: "HNL",
    currencySymbol: "L",
  },
  {
    name: "El Salvador",
    code: "SV",
    phoneCode: "+503",
    currency: "USD",
    currencySymbol: "$",
  },
  {
    name: "Nicaragua",
    code: "NI",
    phoneCode: "+505",
    currency: "NIO",
    currencySymbol: "C$",
  },
  {
    name: "Cuba",
    code: "CU",
    phoneCode: "+53",
    currency: "CUP",
    currencySymbol: "$",
  },
  {
    name: "Jamaica",
    code: "JM",
    phoneCode: "+1",
    currency: "JMD",
    currencySymbol: "$",
  },
  {
    name: "Haiti",
    code: "HT",
    phoneCode: "+509",
    currency: "HTG",
    currencySymbol: "G",
  },
  {
    name: "Trinidad and Tobago",
    code: "TT",
    phoneCode: "+1",
    currency: "TTD",
    currencySymbol: "$",
  },
  {
    name: "Bahamas",
    code: "BS",
    phoneCode: "+1",
    currency: "BSD",
    currencySymbol: "$",
  },
  {
    name: "Barbados",
    code: "BB",
    phoneCode: "+1",
    currency: "BBD",
    currencySymbol: "$",
  },
  {
    name: "Belize",
    code: "BZ",
    phoneCode: "+501",
    currency: "BZD",
    currencySymbol: "$",
  },
  {
    name: "Guyana",
    code: "GY",
    phoneCode: "+592",
    currency: "GYD",
    currencySymbol: "$",
  },
  {
    name: "Suriname",
    code: "SR",
    phoneCode: "+597",
    currency: "SRD",
    currencySymbol: "$",
  },
  {
    name: "Fiji",
    code: "FJ",
    phoneCode: "+679",
    currency: "FJD",
    currencySymbol: "$",
  },
  {
    name: "Papua New Guinea",
    code: "PG",
    phoneCode: "+675",
    currency: "PGK",
    currencySymbol: "K",
  },
  {
    name: "Solomon Islands",
    code: "SB",
    phoneCode: "+677",
    currency: "SBD",
    currencySymbol: "$",
  },
  {
    name: "Vanuatu",
    code: "VU",
    phoneCode: "+678",
    currency: "VUV",
    currencySymbol: "Vt",
  },
  {
    name: "Samoa",
    code: "WS",
    phoneCode: "+685",
    currency: "WST",
    currencySymbol: "T",
  },
  {
    name: "Tonga",
    code: "TO",
    phoneCode: "+676",
    currency: "TOP",
    currencySymbol: "T$",
  },
  {
    name: "Mauritius",
    code: "MU",
    phoneCode: "+230",
    currency: "MUR",
    currencySymbol: "₨",
  },
  {
    name: "Seychelles",
    code: "SC",
    phoneCode: "+248",
    currency: "SCR",
    currencySymbol: "₨",
  },
  {
    name: "Maldives",
    code: "MV",
    phoneCode: "+960",
    currency: "MVR",
    currencySymbol: "ރ.",
  },
  {
    name: "Comoros",
    code: "KM",
    phoneCode: "+269",
    currency: "KMF",
    currencySymbol: "CF",
  },
  {
    name: "Madagascar",
    code: "MG",
    phoneCode: "+261",
    currency: "MGA",
    currencySymbol: "Ar",
  },
  {
    name: "Mauritania",
    code: "MR",
    phoneCode: "+222",
    currency: "MRU",
    currencySymbol: "UM",
  },
  {
    name: "Senegal",
    code: "SN",
    phoneCode: "+221",
    currency: "XOF",
    currencySymbol: "CFA",
  },
  {
    name: "Mali",
    code: "ML",
    phoneCode: "+223",
    currency: "XOF",
    currencySymbol: "CFA",
  },
  {
    name: "Burkina Faso",
    code: "BF",
    phoneCode: "+226",
    currency: "XOF",
    currencySymbol: "CFA",
  },
  {
    name: "Niger",
    code: "NE",
    phoneCode: "+227",
    currency: "XOF",
    currencySymbol: "CFA",
  },
  {
    name: "Côte d'Ivoire",
    code: "CI",
    phoneCode: "+225",
    currency: "XOF",
    currencySymbol: "CFA",
  },
  {
    name: "Togo",
    code: "TG",
    phoneCode: "+228",
    currency: "XOF",
    currencySymbol: "CFA",
  },
  {
    name: "Benin",
    code: "BJ",
    phoneCode: "+229",
    currency: "XOF",
    currencySymbol: "CFA",
  },
  {
    name: "Cameroon",
    code: "CM",
    phoneCode: "+237",
    currency: "XAF",
    currencySymbol: "FCFA",
  },
  {
    name: "Chad",
    code: "TD",
    phoneCode: "+235",
    currency: "XAF",
    currencySymbol: "FCFA",
  },
  {
    name: "Central African Republic",
    code: "CF",
    phoneCode: "+236",
    currency: "XAF",
    currencySymbol: "FCFA",
  },
  {
    name: "Republic of the Congo",
    code: "CG",
    phoneCode: "+242",
    currency: "XAF",
    currencySymbol: "FCFA",
  },
  {
    name: "Gabon",
    code: "GA",
    phoneCode: "+241",
    currency: "XAF",
    currencySymbol: "FCFA",
  },
  {
    name: "Equatorial Guinea",
    code: "GQ",
    phoneCode: "+240",
    currency: "XAF",
    currencySymbol: "FCFA",
  },
  {
    name: "Rwanda",
    code: "RW",
    phoneCode: "+250",
    currency: "RWF",
    currencySymbol: "FRw",
  },
  {
    name: "Burundi",
    code: "BI",
    phoneCode: "+257",
    currency: "BIF",
    currencySymbol: "FBu",
  },
  {
    name: "Democratic Republic of the Congo",
    code: "CD",
    phoneCode: "+243",
    currency: "CDF",
    currencySymbol: "FC",
  },
  {
    name: "Angola",
    code: "AO",
    phoneCode: "+244",
    currency: "AOA",
    currencySymbol: "Kz",
  },
  {
    name: "Mozambique",
    code: "MZ",
    phoneCode: "+258",
    currency: "MZN",
    currencySymbol: "MT",
  },
  {
    name: "Zambia",
    code: "ZM",
    phoneCode: "+260",
    currency: "ZMW",
    currencySymbol: "ZK",
  },
  {
    name: "Zimbabwe",
    code: "ZW",
    phoneCode: "+263",
    currency: "ZWL",
    currencySymbol: "$",
  },
  {
    name: "Malawi",
    code: "MW",
    phoneCode: "+265",
    currency: "MWK",
    currencySymbol: "MK",
  },
  {
    name: "Botswana",
    code: "BW",
    phoneCode: "+267",
    currency: "BWP",
    currencySymbol: "P",
  },
  {
    name: "Namibia",
    code: "NA",
    phoneCode: "+264",
    currency: "NAD",
    currencySymbol: "$",
  },
  {
    name: "Eswatini",
    code: "SZ",
    phoneCode: "+268",
    currency: "SZL",
    currencySymbol: "L",
  },
  {
    name: "Lesotho",
    code: "LS",
    phoneCode: "+266",
    currency: "LSL",
    currencySymbol: "L",
  },
  {
    name: "Liberia",
    code: "LR",
    phoneCode: "+231",
    currency: "LRD",
    currencySymbol: "$",
  },
  {
    name: "Sierra Leone",
    code: "SL",
    phoneCode: "+232",
    currency: "SLL",
    currencySymbol: "Le",
  },
  {
    name: "Guinea",
    code: "GN",
    phoneCode: "+224",
    currency: "GNF",
    currencySymbol: "FG",
  },
  {
    name: "Guinea-Bissau",
    code: "GW",
    phoneCode: "+245",
    currency: "XOF",
    currencySymbol: "CFA",
  },
  {
    name: "The Gambia",
    code: "GM",
    phoneCode: "+220",
    currency: "GMD",
    currencySymbol: "D",
  },
  {
    name: "Cape Verde",
    code: "CV",
    phoneCode: "+238",
    currency: "CVE",
    currencySymbol: "$",
  },
  {
    name: "São Tomé and Príncipe",
    code: "ST",
    phoneCode: "+239",
    currency: "STN",
    currencySymbol: "Db",
  },
  {
    name: "Djibouti",
    code: "DJ",
    phoneCode: "+253",
    currency: "DJF",
    currencySymbol: "Fdj",
  },
  {
    name: "Eritrea",
    code: "ER",
    phoneCode: "+291",
    currency: "ERN",
    currencySymbol: "Nfk",
  },
  {
    name: "Somalia",
    code: "SO",
    phoneCode: "+252",
    currency: "SOS",
    currencySymbol: "Sh",
  },
  {
    name: "Sudan",
    code: "SD",
    phoneCode: "+249",
    currency: "SDG",
    currencySymbol: "ج.س.",
  },
  {
    name: "South Sudan",
    code: "SS",
    phoneCode: "+211",
    currency: "SSP",
    currencySymbol: "£",
  },
  {
    name: "Algeria",
    code: "DZ",
    phoneCode: "+213",
    currency: "DZD",
    currencySymbol: "د.ج",
  },
  {
    name: "Libya",
    code: "LY",
    phoneCode: "+218",
    currency: "LYD",
    currencySymbol: "ل.د",
  },
  {
    name: "Iran",
    code: "IR",
    phoneCode: "+98",
    currency: "IRR",
    currencySymbol: "﷼",
  },
  {
    name: "Iraq",
    code: "IQ",
    phoneCode: "+964",
    currency: "IQD",
    currencySymbol: "ع.د",
  },
  {
    name: "Syria",
    code: "SY",
    phoneCode: "+963",
    currency: "SYP",
    currencySymbol: "£",
  },
  {
    name: "Yemen",
    code: "YE",
    phoneCode: "+967",
    currency: "YER",
    currencySymbol: "﷼",
  },
  {
    name: "Afghanistan",
    code: "AF",
    phoneCode: "+93",
    currency: "AFN",
    currencySymbol: "؋",
  },
  {
    name: "Turkmenistan",
    code: "TM",
    phoneCode: "+993",
    currency: "TMT",
    currencySymbol: "m",
  },
  {
    name: "Uzbekistan",
    code: "UZ",
    phoneCode: "+998",
    currency: "UZS",
    currencySymbol: "лв",
  },
  {
    name: "Tajikistan",
    code: "TJ",
    phoneCode: "+992",
    currency: "TJS",
    currencySymbol: "ЅМ",
  },
  {
    name: "Kyrgyzstan",
    code: "KG",
    phoneCode: "+996",
    currency: "KGS",
    currencySymbol: "с",
  },
  {
    name: "Bhutan",
    code: "BT",
    phoneCode: "+975",
    currency: "BTN",
    currencySymbol: "Nu.",
  },
  {
    name: "Maldives",
    code: "MV",
    phoneCode: "+960",
    currency: "MVR",
    currencySymbol: "ރ.",
  },
  {
    name: "Brunei",
    code: "BN",
    phoneCode: "+673",
    currency: "BND",
    currencySymbol: "$",
  },
  {
    name: "Timor-Leste",
    code: "TL",
    phoneCode: "+670",
    currency: "USD",
    currencySymbol: "$",
  },
  {
    name: "Palau",
    code: "PW",
    phoneCode: "+680",
    currency: "USD",
    currencySymbol: "$",
  },
  {
    name: "Marshall Islands",
    code: "MH",
    phoneCode: "+692",
    currency: "USD",
    currencySymbol: "$",
  },
  {
    name: "Federated States of Micronesia",
    code: "FM",
    phoneCode: "+691",
    currency: "USD",
    currencySymbol: "$",
  },
  {
    name: "Kiribati",
    code: "KI",
    phoneCode: "+686",
    currency: "AUD",
    currencySymbol: "$",
  },
  {
    name: "Nauru",
    code: "NR",
    phoneCode: "+674",
    currency: "AUD",
    currencySymbol: "$",
  },
  {
    name: "Tuvalu",
    code: "TV",
    phoneCode: "+688",
    currency: "AUD",
    currencySymbol: "$",
  },
  {
    name: "Cook Islands",
    code: "CK",
    phoneCode: "+682",
    currency: "NZD",
    currencySymbol: "$",
  },
  {
    name: "Niue",
    code: "NU",
    phoneCode: "+683",
    currency: "NZD",
    currencySymbol: "$",
  },
  {
    name: "Tokelau",
    code: "TK",
    phoneCode: "+690",
    currency: "NZD",
    currencySymbol: "$",
  },
  {
    name: "Vatican City",
    code: "VA",
    phoneCode: "+39",
    currency: "EUR",
    currencySymbol: "€",
  },
  {
    name: "San Marino",
    code: "SM",
    phoneCode: "+378",
    currency: "EUR",
    currencySymbol: "€",
  },
  {
    name: "Monaco",
    code: "MC",
    phoneCode: "+377",
    currency: "EUR",
    currencySymbol: "€",
  },
  {
    name: "Liechtenstein",
    code: "LI",
    phoneCode: "+423",
    currency: "CHF",
    currencySymbol: "CHF",
  },
  {
    name: "Andorra",
    code: "AD",
    phoneCode: "+376",
    currency: "EUR",
    currencySymbol: "€",
  },
  {
    name: "Malta",
    code: "MT",
    phoneCode: "+356",
    currency: "EUR",
    currencySymbol: "€",
  },
  {
    name: "Cyprus",
    code: "CY",
    phoneCode: "+357",
    currency: "EUR",
    currencySymbol: "€",
  },
  {
    name: "Luxembourg",
    code: "LU",
    phoneCode: "+352",
    currency: "EUR",
    currencySymbol: "€",
  },
  {
    name: "Ireland",
    code: "IE",
    phoneCode: "+353",
    currency: "EUR",
    currencySymbol: "€",
  },
  {
    name: "Finland",
    code: "FI",
    phoneCode: "+358",
    currency: "EUR",
    currencySymbol: "€",
  },
  {
    name: "Estonia",
    code: "EE",
    phoneCode: "+372",
    currency: "EUR",
    currencySymbol: "€",
  },
  {
    name: "Latvia",
    code: "LV",
    phoneCode: "+371",
    currency: "EUR",
    currencySymbol: "€",
  },
  {
    name: "Lithuania",
    code: "LT",
    phoneCode: "+370",
    currency: "EUR",
    currencySymbol: "€",
  },
  {
    name: "Slovenia",
    code: "SI",
    phoneCode: "+386",
    currency: "EUR",
    currencySymbol: "€",
  },
  {
    name: "Slovakia",
    code: "SK",
    phoneCode: "+421",
    currency: "EUR",
    currencySymbol: "€",
  },
  {
    name: "Austria",
    code: "AT",
    phoneCode: "+43",
    currency: "EUR",
    currencySymbol: "€",
  },
  {
    name: "Belgium",
    code: "BE",
    phoneCode: "+32",
    currency: "EUR",
    currencySymbol: "€",
  },
  {
    name: "Netherlands",
    code: "NL",
    phoneCode: "+31",
    currency: "EUR",
    currencySymbol: "€",
  },
  {
    name: "Portugal",
    code: "PT",
    phoneCode: "+351",
    currency: "EUR",
    currencySymbol: "€",
  },
  {
    name: "Spain",
    code: "ES",
    phoneCode: "+34",
    currency: "EUR",
    currencySymbol: "€",
  },
  {
    name: "Italy",
    code: "IT",
    phoneCode: "+39",
    currency: "EUR",
    currencySymbol: "€",
  },
  {
    name: "Greece",
    code: "GR",
    phoneCode: "+30",
    currency: "EUR",
    currencySymbol: "€",
  },
  {
    name: "Germany",
    code: "DE",
    phoneCode: "+49",
    currency: "EUR",
    currencySymbol: "€",
  },
  {
    name: "France",
    code: "FR",
    phoneCode: "+33",
    currency: "EUR",
    currencySymbol: "€",
  },
];
