// -----------------------------
// 3️⃣ PROTECTED API ROUTES (METHOD LEVEL)

import { ROLE_DISPLAY_NAMES } from "./roleTransform";

// -----------------------------
const ROLES = ROLE_DISPLAY_NAMES;

const permissions = {
  // ============ USER MANAGEMENT ============
  "/api/users": {
    GET: [ROLES.SECONDARY_ADMIN], // Only secondary admin can view all users
    POST: [ROLES.SECONDARY_ADMIN], // Only secondary admin can create users
    PUT: [ROLES.SECONDARY_ADMIN], // Only secondary admin can update users
    DELETE: [ROLES.SECONDARY_ADMIN], // Only secondary admin can delete users
  },

  // ============ PRODUCTS ============
  "/api/products": {
    GET: [ROLES.SECONDARY_ADMIN, ROLES.SALESMAN, ROLES.STOCK_KEEPER, ROLES.BILLER, ROLES.BILLER_AND_SALESMAN],
    POST: [ROLES.SECONDARY_ADMIN, ROLES.STOCK_KEEPER],
    PUT: [ROLES.SECONDARY_ADMIN, ROLES.STOCK_KEEPER],
    DELETE: [ROLES.SECONDARY_ADMIN],
  },

  // ============ ADMIN ============
  "/api/admin": {
    GET: [ROLES.SECONDARY_ADMIN],
    POST: [ROLES.SECONDARY_ADMIN],
    PUT: [ROLES.SECONDARY_ADMIN],
    DELETE: [ROLES.SECONDARY_ADMIN],
  },

  // ============ PARTY/CUSTOMERS ============
  "/api/party": {
    GET: [ROLES.SECONDARY_ADMIN, ROLES.SALESMAN, ROLES.BILLER, ROLES.BILLER_AND_SALESMAN, ROLES.CA_ACCOUNTANT],
    POST: [ROLES.SECONDARY_ADMIN, ROLES.SALESMAN, ROLES.BILLER],
    PUT: [ROLES.SECONDARY_ADMIN, ROLES.SALESMAN, ROLES.BILLER],
    DELETE: [ROLES.SECONDARY_ADMIN, ROLES.SALESMAN, ROLES.BILLER],
  },

  // ============ MEDIA/IMAGES ============
  "/api/media/images": {
    GET: [ROLES.SECONDARY_ADMIN, ROLES.SALESMAN, ROLES.STOCK_KEEPER, ROLES.BILLER, ROLES.BILLER_AND_SALESMAN],
    POST: [ROLES.SECONDARY_ADMIN, ROLES.STOCK_KEEPER, ROLES.SALESMAN],
    DELETE: [ROLES.SECONDARY_ADMIN, ROLES.STOCK_KEEPER],
  },

  // ============ CASH ADJUSTMENT ============
  "/api/cashadjustment": {
    GET: [ROLES.SECONDARY_ADMIN, ROLES.CA_ACCOUNTANT, ROLES.CA_ACCOUNT_EDIT_ACCESS],
    POST: [ROLES.SECONDARY_ADMIN, ROLES.CA_ACCOUNTANT, ROLES.CA_ACCOUNT_EDIT_ACCESS],
  },
  
  "/api/cashadjustment/[id]": {
    GET: [ROLES.SECONDARY_ADMIN, ROLES.CA_ACCOUNTANT, ROLES.CA_ACCOUNT_EDIT_ACCESS],
    PUT: [ROLES.SECONDARY_ADMIN, ROLES.CA_ACCOUNT_EDIT_ACCESS],
    DELETE: [ROLES.SECONDARY_ADMIN],
  },
  
  "/api/cashadjustment/delete-transaction": {
    DELETE: [ROLES.SECONDARY_ADMIN],
  },
  
  "/api/cashadjustment/edit-transaction": {
    PUT: [ROLES.SECONDARY_ADMIN, ROLES.CA_ACCOUNT_EDIT_ACCESS],
  },

  // ============ CASH AND BANK ============
  "/api/cashandbank": {
    GET: [ROLES.SECONDARY_ADMIN, ROLES.CA_ACCOUNTANT, ROLES.CA_ACCOUNT_EDIT_ACCESS],
    POST: [ROLES.SECONDARY_ADMIN, ROLES.CA_ACCOUNTANT, ROLES.CA_ACCOUNT_EDIT_ACCESS],
  },
  
  "/api/cashandbank/[id]": {
    GET: [ROLES.SECONDARY_ADMIN, ROLES.CA_ACCOUNTANT, ROLES.CA_ACCOUNT_EDIT_ACCESS],
    PUT: [ROLES.SECONDARY_ADMIN, ROLES.CA_ACCOUNT_EDIT_ACCESS],
    DELETE: [ROLES.SECONDARY_ADMIN],
  },

  // ============ CATEGORIES ============
  "/api/categories": {
    GET: [ROLES.SECONDARY_ADMIN, ROLES.SALESMAN, ROLES.STOCK_KEEPER, ROLES.BILLER, ROLES.BILLER_AND_SALESMAN],
    POST: [ROLES.SECONDARY_ADMIN, ROLES.STOCK_KEEPER],
  },
  
  "/api/categories/[id]": {
    GET: [ROLES.SECONDARY_ADMIN, ROLES.SALESMAN, ROLES.STOCK_KEEPER, ROLES.BILLER, ROLES.BILLER_AND_SALESMAN],
    PUT: [ROLES.SECONDARY_ADMIN, ROLES.STOCK_KEEPER],
    DELETE: [ROLES.SECONDARY_ADMIN],
  },

  // ============ ITEMS ============
  "/api/items": {
    GET: [ROLES.SECONDARY_ADMIN, ROLES.SALESMAN, ROLES.STOCK_KEEPER, ROLES.BILLER, ROLES.BILLER_AND_SALESMAN],
    POST: [ROLES.SECONDARY_ADMIN, ROLES.STOCK_KEEPER],
  },
  
  "/api/items/[id]": {
    GET: [ROLES.SECONDARY_ADMIN, ROLES.SALESMAN, ROLES.STOCK_KEEPER, ROLES.BILLER, ROLES.BILLER_AND_SALESMAN],
    PUT: [ROLES.SECONDARY_ADMIN, ROLES.STOCK_KEEPER],
    DELETE: [ROLES.SECONDARY_ADMIN],
  },

  // ============ PURCHASE ============
  "/api/purchase": {
    POST: [ROLES.SECONDARY_ADMIN, ROLES.STOCK_KEEPER],
  },
  
  "/api/purchase-init-data": {
    GET: [ROLES.SECONDARY_ADMIN, ROLES.STOCK_KEEPER, ROLES.BILLER],
  },

  // ============ TRANSACTIONS ============
  "/api/transaction": {
    GET: [ROLES.SECONDARY_ADMIN, ROLES.CA_ACCOUNTANT, ROLES.CA_ACCOUNT_EDIT_ACCESS, ROLES.BILLER],
    POST: [ROLES.SECONDARY_ADMIN, ROLES.BILLER, ROLES.CA_ACCOUNTANT, ROLES.CA_ACCOUNT_EDIT_ACCESS],
  },
  
  "/api/transaction/[id]": {
    GET: [ROLES.SECONDARY_ADMIN, ROLES.CA_ACCOUNTANT, ROLES.CA_ACCOUNT_EDIT_ACCESS, ROLES.BILLER],
    PUT: [ROLES.SECONDARY_ADMIN, ROLES.CA_ACCOUNT_EDIT_ACCESS],
    DELETE: [ROLES.SECONDARY_ADMIN],
  },

  // ============ COMPANY/SHOP SETTINGS ============
  "/api/company/edit-shop": {
    GET: [ROLES.SECONDARY_ADMIN],
    PUT: [ROLES.SECONDARY_ADMIN],
  },
};

export default permissions;